version: '3.8'

services:
  # Node.js server (your app)
  node-app:
    build: .
    container_name: node-app
    ports:
      - "3000:3000"  # Expose local port 3000
    depends_on:
      - openvidu-server  # Ensure OpenVidu server starts before Node.js app
    environment:
      - OPENVIDU_URL=http://localhost:4443  # Use internal service name for OpenVidu URL
      - OPENVIDU_SECRET=MY_SECRET  # Secret for OpenVidu
    networks:
      - app-network  # Use shared network

  # OpenVidu Server
  openvidu-server:
    image: openvidu/openvidu-server-kms:latest
    container_name: openvidu-server
    environment:
      - OPENVIDU_SECRET=MY_SECRET  # Secret for OpenVidu server
      - OPENVIDU_CERTIFICATE_TYPE=selfsigned  # For testing, you can use a self-signed certificate
      - OPENVIDU_DOMAIN_OR_PUBLIC_IP=localhost
    ports:
      - "4443:4443"  # Expose local port 4443 for HTTPS
    networks:
      - app-network  # Use shared network
    volumes:
      - /dev/shm:/dev/shm  # Necessary for WebRTC performance, optional but recommended

# Define a shared network for communication between services
networks:
  app-network:
    driver: bridge
