version: '3.8'

services:
  # Backend (Node.js server)
  node-app:
    build: ./backend
    container_name: node-app
    ports:
      - "3000:3000"  # Expose local port 3000
    depends_on:
      - openvidu-server  # Ensure OpenVidu server starts before Node.js app
    environment:
      - OPENVIDU_URL=http://openvidu-server:4443
      - OPENVIDU_SECRET=MY_SECRET  # Secret for OpenVidu
      - CORS_ORIGIN=http://164.90.228.80:5173  # Allow CORS from your client
    networks:
      - app-network  # Use shared network

  # OpenVidu Server
  openvidu-server:
    image: openvidu/openvidu-server-kms:latest
    container_name: openvidu-server
    environment:
      - OPENVIDU_SECRET=MY_SECRET  # Secret for OpenVidu server
      - OPENVIDU_CERTIFICATE_TYPE=selfsigned  # For testing, self-signed certificate
      - OPENVIDU_DOMAIN_OR_PUBLIC_IP=164.90.228.80  # Use your DigitalOcean IP
      - HTTPS_PORT=4443
    ports:
      - "4443:4443"  # Expose local port 4443 for HTTPS
    networks:
      - app-network  # Use shared network
    volumes:
      - /dev/shm:/dev/shm  # Necessary for WebRTC performance, optional but recommended

  # Frontend (React client)
  client:
    build: ./client
    container_name: client
    ports:
      - "5173:5173"  # Vite default port
    depends_on:
      - node-app
    networks:
      - app-network
    environment:
      - VITE_API_URL=http://164.90.228.80:3000  # Use your DigitalOcean IP
    volumes:
      - ./client:/app  # Mount the client directory for live updates
      - /app/node_modules

networks:
  app-network:
    driver: bridge