version: '3.8'

services:
  # Backend (Node.js server)
  node-app:
    build: ./backend
    container_name: node-app
    ports:
      - "3000:3000"  # Expose local port 3000
    depends_on:
      - openvidu-server  # Ensure OpenVidu server starts before Node.js app
    environment:
      - OPENVIDU_URL=http://openvidu-server:4443  # Use service name for internal OpenVidu URL
      - OPENVIDU_SECRET=MY_SECRET  # Secret for OpenVidu
    networks:
      - app-network  # Use shared network

  # OpenVidu Server
  openvidu-server:
    image: openvidu/openvidu-server-kms:latest
    container_name: openvidu-server
    environment:
      - OPENVIDU_SECRET=MY_SECRET  # Secret for OpenVidu server
      - OPENVIDU_CERTIFICATE_TYPE=selfsigned  # For testing, self-signed certificate
      - OPENVIDU_DOMAIN_OR_PUBLIC_IP=localhost
    ports:
      - "4443:4443"  # Expose local port 4443 for HTTPS
    networks:
      - app-network  # Use shared network
    volumes:
      - /dev/shm:/dev/shm  # Necessary for WebRTC performance, optional but recommended

  # Frontend (React client)
  client:
    build: ./client
    container_name: client
    ports:
      - "5173:5173"  # Vite default port
    depends_on:
      - node-app
    networks:
      - app-network
    environment:
      - VITE_API_URL=http://node-app:3000  # Link frontend with backend using service name
    volumes:
      - ./client:/app  # Mount the client directory for live updates
      - /app/node_modules

# Define a shared network for communication between services
networks:
  app-network:
    driver: bridge
